
-- Execute this script while truncating T_LOAN or T_CUSTOMER table

TRUNCATE TABLE T_LOAN
TRUNCATE TABLE T_CUSTOMER
TRUNCATE TABLE T_CUSTOMER_AUDIT
TRUNCATE TABLE T_EXISTING_LIABILITY
TRUNCATE TABLE T_COMMENT
TRUNCATE TABLE T_LOAN_DOCUMENT