var rowEditing = Ext.create('Ext.grid.plugin.RowEditing', {
			clicksToMoveEditor: 1,
			autoCancel: false
		});
/*
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Desktop.view.loan.AdminPanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.adminPanel',

	requires: [
		'Ext.tab.Panel',
		'Ext.tab.Tab',
		'Ext.grid.Panel',
		'Ext.grid.column.Boolean',
		'Ext.toolbar.Toolbar',
		'Ext.form.field.Text',
		'Ext.tree.Panel',
		'Ext.tree.View',
		'Ext.grid.filters.filter.Number',
		'Ext.grid.column.Date',
		'Ext.grid.filters.filter.Date',
		'Ext.grid.filters.filter.String',
		'Ext.grid.filters.filter.Boolean',
		'Ext.selection.CheckboxModel',
		'Ext.grid.filters.Filters',
		'Ext.grid.feature.Summary',
	],

	layout: 'fit',
	items: 
	[
	    {
            xtype: 'tabpanel',
            layout: 'fit',
            tabPosition : 'bottom',
            items:[
            	/*{
            		xtype: 'naztechAdmin',
            		title: 'Naztech Administration',
            		hidden : true
            	},*/
     			{
     				xtype: 'businessAdmin',
     				title: 'Business Administration',
     			},
            	{
            		xtype: 'techAdmin',
            		title: 'Tech Administration',
            	}
            ]
	    },
	    
		  
    ]

  });