package com.naztech.lms.constants;
public interface IPrefConstants {
	
	 static final String ACT_PREFERENCE = "ACT_preferance";
	 static final String GET_PREFERENCE = "GET_preference";
	 static final String SEL_PREFERENCE = "SEL_preference";
	 static final String RS_TYPE_PREFERENCE = "RS_TYPE_PREFERENCE";
	
	 static String MAP_GROUP_NAME_KEY_OFAC_SWIFT = "OFAC_SWIFT";
	 static String MAP_GROUP_NAME_KEY_OFAC_KYC = "OFAC_KYC";
	 static  String MAP_GROUP_NAME_KEY_SYS_PREF = "SYS_PREF";
	 static  String MAP_GROUP_NAME_KEY_LOGIN_PREF = "LOGIN_PREF";
	 static  String MAP_GROUP_NAME_KEY_OFAC_REMITTANCE = "OFAC_REMITTANCE";
	
	 static String MAP_VALUE_NAME_KEY_CHECK_RMA = "CHECK_RMA";
	 static String MAP_VALUE_NAME_KEY_DATA_SHOW_FROM_DATE = "DATA_SHOW_FROM_DATE";
	 static String MAP_VALUE_NAME_KEY_IS_DB_AUTH = "IS_DB_AUTH";
	 static String MAP_VALUE_NAME_KEY_IS_IP_AUTH = "IS_IP_AUTH";
	 static String MAP_VALUE_NAME_KEY_IS_LOGIN_AUTHENTICATE_VIA_EMAIL = "IS_LOGIN_AUTHENTICATE_VIA_EMAIL";
	 static String MAP_VALUE_NAME_KEY_IS_LOGIN_AUTHENTICATE_VIA_SMS = "IS_LOGIN_AUTHENTICATE_VIA_SMS";
	 static String MAP_VALUE_NAME_KEY_IS_TWO_FACTOR_LOGIN = "IS_TWO_FACTOR_LOGIN";
	 static String MAP_VALUE_NAME_KEY_SEARCH_TYPE = "SEARCH_TYPE";
	 static String MAP_VALUE_NAME_KEY_MAX_CONCURRENT_USER = "MAX_CONCURRENT_USER";

}